/***************************************************************************//**
* \file TEST_MODEL_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains TEST_MODEL model data.
* Date: 2022-10-27 14:54:59.274295
*******************************************************************************
* \copyright
* Copyright 2022, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef TEST_MODEL_TFLM_MODEL_INT8X8_H
#define TEST_MODEL_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t TEST_MODEL_model_bin[];
#else
extern uint8_t TEST_MODEL_model_bin[];
#endif // CY_ML_MODEL_MEM
#define TEST_MODEL_MODEL_BIN_LEN (11088u)
#define TEST_MODEL_ARENA_SIZE (19713u)

#endif // TEST_MODEL_TFLM_MODEL_INT8X8_H

