/***************************************************************************//**
* \file TEST_MODEL_ifx_y_data_int16x16.h
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the TEST_MODEL model in int16x16 representation.
* Date: 2022-09-29 08:03:31.436385
*******************************************************************************
* \copyright
* Copyright 2022, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef TEST_MODEL_IFX_Y_DATA_INT16X16_H
#define TEST_MODEL_IFX_Y_DATA_INT16X16_H

#include <stdint.h>


extern const uint8_t TEST_MODEL_y_data_bin[];
#define TEST_MODEL_Y_DATA_BIN_LEN 2000

#endif // TEST_MODEL_IFX_Y_DATA_INT16X16_H
