/***************************************************************************//**
* \file MAGIC_WAND_tflm_x_data_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the MAGIC_WAND model in int8x8 representation.
* Date: 2023-08-30 18:28:25.471845
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MAGIC_WAND_TFLM_X_DATA_INT8X8_H
#define MAGIC_WAND_TFLM_X_DATA_INT8X8_H

#include <stdint.h>


extern const uint8_t MAGIC_WAND_x_data_bin[];
#define MAGIC_WAND_X_DATA_BIN_LEN (768016)

#endif // MAGIC_WAND_TFLM_X_DATA_INT8X8_H

