/***************************************************************************//**
* \file TEST_MODEL_tflm_y_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the TEST_MODEL model in float representation.
* Date: 2022-10-27 14:54:59.791921
*******************************************************************************
* \copyright
* Copyright 2022, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef TEST_MODEL_TFLM_Y_DATA_FLOAT_H
#define TEST_MODEL_TFLM_Y_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t TEST_MODEL_y_data_bin[];
#define TEST_MODEL_Y_DATA_BIN_LEN (1600)

#endif // TEST_MODEL_TFLM_Y_DATA_FLOAT_H

