/***************************************************************************//**
* \file TEST_MODEL_tflm_x_data_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the TEST_MODEL model in int8x8 representation.
* Date: 2022-10-27 14:54:59.924932
*******************************************************************************
* \copyright
* Copyright 2022, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef TEST_MODEL_TFLM_X_DATA_INT8X8_H
#define TEST_MODEL_TFLM_X_DATA_INT8X8_H

#include <stdint.h>


extern const uint8_t TEST_MODEL_x_data_bin[];
#define TEST_MODEL_X_DATA_BIN_LEN (76816)

#endif // TEST_MODEL_TFLM_X_DATA_INT8X8_H

