/***************************************************************************//**
* \file MAGIC_WAND_tflm_x_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the MAGIC_WAND model in float representation.
* Date: 2022-10-27 15:22:54.121715
*******************************************************************************
* \copyright
* Copyright 2022, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MAGIC_WAND_TFLM_X_DATA_FLOAT_H
#define MAGIC_WAND_TFLM_X_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t MAGIC_WAND_x_data_bin[];
#define MAGIC_WAND_X_DATA_BIN_LEN (3072016)

#endif // MAGIC_WAND_TFLM_X_DATA_FLOAT_H

