/***************************************************************************//**
* \file TEST_MODEL_ifx_x_data_int16x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the TEST_MODEL model in int16x8 representation.
* Date: 2022-09-29 08:03:31.600379
*******************************************************************************
* \copyright
* Copyright 2022, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef TEST_MODEL_IFX_X_DATA_INT16X8_H
#define TEST_MODEL_IFX_X_DATA_INT16X8_H

#include <stdint.h>


extern const uint8_t TEST_MODEL_x_data_bin[];
#define TEST_MODEL_X_DATA_BIN_LEN 156816

#endif // TEST_MODEL_IFX_X_DATA_INT16X8_H
